const VOCAB = [
  {id:'binario', it:'binario', zh:'月台 / track', topic:'火車', emoji:'🚆', example:'Dov\'è il binario?', exZh:'月台喺邊？'},
  {id:'stazione', it:'stazione', zh:'車站', topic:'火車', emoji:'🚉', example:'Dov\'è la stazione?', exZh:'車站喺邊？'},
  {id:'uscita', it:'uscita', zh:'出口', topic:'問路', emoji:'🚪', example:'Dov\'è l\'uscita?', exZh:'出口喺邊？'},
  {id:'bagno', it:'bagno', zh:'廁所', topic:'問路', emoji:'🚻', example:'Dov\'è il bagno?', exZh:'廁所喺邊？'},
  {id:'conto', it:'conto', zh:'帳單 / 埋單', topic:'餐廳', emoji:'🧾', example:'Il conto, per favore.', exZh:'埋單，唔該。'},
  {id:'carta', it:'carta', zh:'卡', topic:'付款', emoji:'💳', example:'Posso pagare con la carta?', exZh:'可以用卡付款嗎？'},
  {id:'contanti', it:'contanti', zh:'現金', topic:'付款', emoji:'💶', example:'Posso pagare in contanti?', exZh:'可以畀現金嗎？'},
  {id:'acqua', it:'acqua', zh:'水', topic:'飲品', emoji:'💧', example:'Vorrei un\'acqua.', exZh:'我想要一支水。'},
  {id:'frizzante', it:'frizzante', zh:'有氣 / sparkling', topic:'飲品', emoji:'🫧', example:'Avete acqua frizzante?', exZh:'有冇有氣水？'},
  {id:'naturale', it:'naturale', zh:'無氣 / still', topic:'飲品', emoji:'💧', example:'Vorrei acqua naturale.', exZh:'我要無氣水。'},
  {id:'birra', it:'birra', zh:'啤酒', topic:'飲品', emoji:'🍺', example:'Vorrei una birra, per favore.', exZh:'我想要一杯啤酒。'},
  {id:'vino', it:'vino', zh:'酒 / wine', topic:'飲品', emoji:'🍷', example:'Prendo un vino rosso.', exZh:'我要一杯紅酒。'},
  {id:'rosso', it:'rosso', zh:'紅色 / 紅酒用', topic:'飲品', emoji:'🔴', example:'Un vino rosso, per favore.', exZh:'一杯紅酒，唔該。'},
  {id:'bianco', it:'bianco', zh:'白色 / 白酒用', topic:'飲品', emoji:'⚪', example:'Un vino bianco, per favore.', exZh:'一杯白酒，唔該。'},
  {id:'ghiaccio', it:'ghiaccio', zh:'冰', topic:'飲品', emoji:'🧊', example:'Senza ghiaccio, per favore.', exZh:'唔要冰，唔該。'},
  {id:'zucchero', it:'zucchero', zh:'糖', topic:'餐廳', emoji:'🍬', example:'Senza zucchero.', exZh:'唔要糖。'},
  {id:'latte', it:'latte', zh:'奶', topic:'Café', emoji:'🥛', example:'Senza latte.', exZh:'唔要奶。'},
  {id:'caffe', it:'caffè', zh:'咖啡 / espresso', topic:'Café', emoji:'☕', example:'Vorrei un caffè, per favore.', exZh:'我想要一杯咖啡。'},
  {id:'quanto', it:'quanto costa', zh:'幾錢', topic:'購物', emoji:'🏷️', example:'Quanto costa?', exZh:'幾錢？'},
  {id:'caro', it:'caro', zh:'貴', topic:'購物', emoji:'💸', example:'È troppo caro.', exZh:'太貴喇。'},
  {id:'economico', it:'economico', zh:'平 / 經濟實惠', topic:'購物', emoji:'🪙', example:'Avete qualcosa di più economico?', exZh:'有冇平啲嘅？'},
  {id:'biglietto', it:'biglietto', zh:'車票 / 門票', topic:'火車', emoji:'🎫', example:'Un biglietto per Roma, per favore.', exZh:'一張去羅馬嘅飛，唔該。'},
  {id:'parte', it:'parte', zh:'出發', topic:'火車', emoji:'🕒', example:'A che ora parte?', exZh:'幾點出發？'},
  {id:'arriva', it:'arriva', zh:'到達', topic:'火車', emoji:'📍', example:'A che ora arriva a Roma?', exZh:'幾點到羅馬？'},
  {id:'treno', it:'treno', zh:'火車', topic:'火車', emoji:'🚄', example:'Questo treno va a Venezia?', exZh:'呢班火車去威尼斯嗎？'},
  {id:'capisco', it:'non capisco', zh:'我唔明', topic:'求助', emoji:'🤷', example:'Mi dispiace, non capisco.', exZh:'唔好意思，我唔明。'},
  {id:'ripetere', it:'ripetere', zh:'再講一次', topic:'求助', emoji:'🔁', example:'Può ripetere, per favore?', exZh:'可以再講一次嗎？'},
  {id:'lentamente', it:'lentamente', zh:'慢慢地', topic:'求助', emoji:'🐢', example:'Più lentamente, per favore.', exZh:'慢啲，唔該。'},
  {id:'vorrei', it:'vorrei', zh:'我想要', topic:'餐廳', emoji:'👉', example:'Vorrei questo.', exZh:'我想要呢個。'},
  {id:'consiglia', it:'consiglia', zh:'推薦', topic:'餐廳', emoji:'⭐', example:'Cosa ci consiglia?', exZh:'你有咩推薦？'},
  {id:'piccante', it:'piccante', zh:'辣', topic:'餐廳', emoji:'🌶️', example:'È piccante?', exZh:'呢個辣唔辣？'},
  {id:'maiale', it:'maiale', zh:'豬肉', topic:'餐廳', emoji:'🐷', example:'C\'è del maiale?', exZh:'有冇豬肉？'},
  {id:'senza', it:'senza', zh:'唔要 / without', topic:'餐廳', emoji:'🚫', example:'Senza formaggio, per favore.', exZh:'唔要芝士，唔該。'},
  {id:'per-favore', it:'per favore', zh:'唔該 / please', topic:'基本', emoji:'🙏', example:'Un caffè, per favore.', exZh:'一杯咖啡，唔該。'},
  {id:'grazie', it:'grazie', zh:'多謝', topic:'基本', emoji:'🙌', example:'Grazie mille.', exZh:'非常多謝。'},
  {id:'buongiorno', it:'buongiorno', zh:'早晨 / 日安', topic:'基本', emoji:'🌤️', example:'Buongiorno!', exZh:'早晨！'},
  {id:'dove', it:'dov\'è', zh:'喺邊？', topic:'問路', emoji:'🧭', example:'Dov\'è la stazione?', exZh:'車站喺邊？'},
  {id:'roma', it:'Roma', zh:'羅馬', topic:'火車', emoji:'🏛️', example:'Questo treno va a Roma?', exZh:'呢班火車去羅馬嗎？'},
  {id:'venezia', it:'Venezia', zh:'威尼斯', topic:'火車', emoji:'🛶', example:'Questo treno va a Venezia?', exZh:'呢班火車去威尼斯嗎？'},
  {id:'questo', it:'questo', zh:'呢個', topic:'基本', emoji:'👆', example:'Vorrei questo.', exZh:'我想要呢個。'},
  {id:'camera', it:'camera', zh:'房間', topic:'酒店', emoji:'🛏️', example:'Avete una camera?', exZh:'有冇房？'},
  {id:'stasera', it:'stasera', zh:'今晚', topic:'酒店', emoji:'🌙', example:'Una camera per stasera.', exZh:'今晚一間房。'},
  {id:'formaggio', it:'formaggio', zh:'芝士', topic:'餐廳', emoji:'🧀', example:'Senza formaggio.', exZh:'唔要芝士。'},
  {id:'menu', it:'menù', zh:'餐牌', topic:'餐廳', emoji:'📖', example:'Il menù, per favore.', exZh:'餐牌，唔該。'},
  {id:'tavolo', it:'tavolo', zh:'枱', topic:'餐廳', emoji:'🍽️', example:'Un tavolo per due, per favore.', exZh:'兩位，唔該。'},
  {id:'due', it:'due', zh:'二 / 兩個', topic:'基本', emoji:'2️⃣', example:'Due birre, per favore.', exZh:'兩杯啤酒，唔該。'},
  {id:'ora', it:'a che ora', zh:'幾點', topic:'火車', emoji:'⏰', example:'A che ora parte?', exZh:'幾點出發？'},
  {id:'sinistra', it:'sinistra', zh:'左邊', topic:'問路', emoji:'⬅️', example:'A sinistra.', exZh:'喺左邊。'},
  {id:'destra', it:'destra', zh:'右邊', topic:'問路', emoji:'➡️', example:'A destra.', exZh:'喺右邊。'},
  {id:'dritto', it:'dritto', zh:'直行', topic:'問路', emoji:'⬆️', example:'Sempre dritto.', exZh:'一直直行。'}
];
