const VOCAB = [
  // 基本交流
  {id:'buongiorno', it:'buongiorno', zh:'早晨 / 日安', topic:'基本', emoji:'🌤️', example:'Buongiorno!', exZh:'早晨！'},
  {id:'grazie', it:'grazie', zh:'多謝', topic:'基本', emoji:'🙌', example:'Grazie mille.', exZh:'非常多謝。'},
  {id:'prego', it:'prego', zh:'唔使客氣 / 請', topic:'基本', emoji:'🙂', example:'Prego.', exZh:'唔使客氣。'},
  {id:'per-favore', it:'per favore', zh:'唔該 / please', topic:'基本', emoji:'🙏', example:'Un caffè, per favore.', exZh:'一杯咖啡，唔該。'},
  {id:'va-bene', it:'va bene', zh:'好 / OK', topic:'基本', emoji:'👌', example:'Va bene, grazie.', exZh:'好，多謝。'},
  {id:'questo', it:'questo', zh:'呢個', topic:'基本', emoji:'👆', example:'Vorrei questo.', exZh:'我想要呢個。'},
  {id:'due', it:'due', zh:'兩個 / two', topic:'基本', emoji:'2️⃣', example:'Un tavolo per due, per favore.', exZh:'兩位，唔該。'},
  {id:'vorrei', it:'vorrei', zh:'我想要 / I would like', topic:'基本', emoji:'👉', example:'Vorrei questo, per favore.', exZh:'我想要呢個，唔該。'},
  {id:'posso-avere', it:'posso avere', zh:'可以俾我……嗎？', topic:'基本', emoji:'🙋', example:'Posso avere un bicchiere?', exZh:'可以俾我一隻杯嗎？'},
  {id:'mi-dispiace', it:'mi dispiace', zh:'對唔住 / 唔好意思', topic:'求助', emoji:'😔', example:'Mi dispiace, non capisco.', exZh:'唔好意思，我唔明。'},
  {id:'non-capisco', it:'non capisco', zh:'我唔明', topic:'求助', emoji:'🤷', example:'Mi dispiace, non capisco.', exZh:'唔好意思，我唔明。'},
  {id:'ripetere', it:'ripetere', zh:'重複 / 再講一次', topic:'求助', emoji:'🔁', example:'Può ripetere, per favore?', exZh:'可以再講一次嗎？'},
  {id:'lentamente', it:'lentamente', zh:'慢慢地', topic:'求助', emoji:'🐢', example:'Più lentamente, per favore.', exZh:'慢啲，唔該。'},
  {id:'aiuto', it:'aiuto', zh:'救命 / 幫手', topic:'求助', emoji:'🆘', example:'Aiuto, per favore!', exZh:'幫幫手，唔該！'},

  // 問路 / 位置
  {id:'dove', it:"dov'è", zh:'喺邊？', topic:'問路', emoji:'🧭', example:"Dov'è la stazione?", exZh:'車站喺邊？'},
  {id:'stazione', it:'stazione', zh:'車站', topic:'火車', emoji:'🚉', example:"Dov'è la stazione?", exZh:'車站喺邊？'},
  {id:'binario', it:'binario', zh:'月台 / track', topic:'火車', emoji:'🚆', example:"Dov'è il binario?", exZh:'月台喺邊？'},
  {id:'uscita', it:'uscita', zh:'出口', topic:'問路', emoji:'🚪', example:"Dov'è l'uscita?", exZh:'出口喺邊？'},
  {id:'bagno', it:'bagno', zh:'廁所', topic:'問路', emoji:'🚻', example:"Dov'è il bagno?", exZh:'廁所喺邊？'},
  {id:'destra', it:'destra', zh:'右邊', topic:'問路', emoji:'➡️', example:'A destra.', exZh:'喺右邊。'},
  {id:'sinistra', it:'sinistra', zh:'左邊', topic:'問路', emoji:'⬅️', example:'A sinistra.', exZh:'喺左邊。'},
  {id:'dritto', it:'dritto', zh:'直行', topic:'問路', emoji:'⬆️', example:'Sempre dritto.', exZh:'一直直行。'},
  {id:'dietro', it:'dietro', zh:'後面 / behind', topic:'問路', emoji:'↩️', example:'È dietro la chiesa.', exZh:'喺教堂後面。'},
  {id:'vicino', it:'vicino', zh:'近', topic:'問路', emoji:'📍', example:'È vicino?', exZh:'近唔近？'},
  {id:'lontano', it:'lontano', zh:'遠', topic:'問路', emoji:'🗺️', example:'È lontano?', exZh:'遠唔遠？'},
  {id:'chiesa', it:'chiesa', zh:'教堂', topic:'問路', emoji:'⛪', example:"Dov'è la chiesa?", exZh:'教堂喺邊？'},
  {id:'panificio', it:'panificio', zh:'麵包店', topic:'問路', emoji:'🥖', example:"Dov'è il panificio?", exZh:'麵包店喺邊？'},
  {id:'mercato', it:'mercato', zh:'市場', topic:'問路', emoji:'🛒', example:"Dov'è il mercato?", exZh:'市場喺邊？'},

  // 火車 / 交通
  {id:'treno', it:'treno', zh:'火車', topic:'火車', emoji:'🚄', example:'Questo treno va a Venezia?', exZh:'呢班火車去威尼斯嗎？'},
  {id:'biglietto', it:'biglietto', zh:'車票 / 門票', topic:'火車', emoji:'🎫', example:'Un biglietto per Roma, per favore.', exZh:'一張去羅馬嘅飛，唔該。'},
  {id:'a-che-ora', it:'a che ora', zh:'幾點？', topic:'火車', emoji:'⏰', example:'A che ora parte?', exZh:'幾點出發？'},
  {id:'parte', it:'parte', zh:'出發', topic:'火車', emoji:'🕒', example:'A che ora parte?', exZh:'幾點出發？'},
  {id:'arriva', it:'arriva', zh:'到達', topic:'火車', emoji:'📍', example:'A che ora arriva a Roma?', exZh:'幾點到羅馬？'},
  {id:'ritardo', it:'ritardo', zh:'延誤 / 遲到', topic:'火車', emoji:'⏳', example:'Il treno è in ritardo?', exZh:'班火車有冇延誤？'},

  // 餐廳 / 點餐
  {id:'prenotazione', it:'prenotazione', zh:'預約', topic:'餐廳', emoji:'📅', example:'Ho una prenotazione.', exZh:'我有預約。'},
  {id:'pranzo', it:'pranzo', zh:'午餐', topic:'餐廳', emoji:'🍝', example:'A che ora è il pranzo?', exZh:'午餐幾點？'},
  {id:'cena', it:'cena', zh:'晚餐', topic:'餐廳', emoji:'🍽️', example:'Una prenotazione per cena.', exZh:'晚餐嘅預約。'},
  {id:'tavolo', it:'tavolo', zh:'枱', topic:'餐廳', emoji:'🍽️', example:'Un tavolo per due, per favore.', exZh:'兩位，唔該。'},
  {id:'menu', it:'menù', zh:'餐牌', topic:'餐廳', emoji:'📖', example:'Il menù, per favore.', exZh:'餐牌，唔該。'},
  {id:'consiglia', it:'consiglia', zh:'推薦', topic:'餐廳', emoji:'⭐', example:'Cosa ci consiglia?', exZh:'你有咩推薦？'},
  {id:'conto', it:'conto', zh:'帳單 / 埋單', topic:'餐廳', emoji:'🧾', example:'Il conto, per favore.', exZh:'埋單，唔該。'},
  {id:'tovagliolo', it:'tovagliolo', zh:'餐巾', topic:'餐廳', emoji:'🧻', example:'Posso avere un tovagliolo?', exZh:'可以俾我一張餐巾嗎？'},
  {id:'forchetta', it:'forchetta', zh:'叉', topic:'餐廳', emoji:'🍴', example:'Posso avere una forchetta?', exZh:'可以俾我一隻叉嗎？'},
  {id:'bicchiere', it:'bicchiere', zh:'杯', topic:'餐廳', emoji:'🥛', example:'Posso avere un bicchiere?', exZh:'可以俾我一隻杯嗎？'},
  {id:'mangiare', it:'mangiare', zh:'食 / to eat', topic:'餐廳', emoji:'🍴', example:'Vorrei mangiare qui.', exZh:'我想喺呢度食。'},
  {id:'bere', it:'bere', zh:'飲 / to drink', topic:'餐廳', emoji:'🥤', example:'Vorrei qualcosa da bere.', exZh:'我想要啲飲品。'},
  {id:'da-bere', it:'da bere', zh:'飲品 / 喝的東西', topic:'餐廳', emoji:'🥤', example:'Qualcosa da bere?', exZh:'要唔要啲飲品？'},
  {id:'prendo', it:'prendo', zh:'我要 / 我揀', topic:'餐廳', emoji:'☝️', example:'Prendo questo.', exZh:'我要呢個。'},
  {id:'senza', it:'senza', zh:'唔要 / without', topic:'餐廳', emoji:'🚫', example:'Senza formaggio, per favore.', exZh:'唔要芝士，唔該。'},
  {id:'formaggio', it:'formaggio', zh:'芝士', topic:'餐廳', emoji:'🧀', example:'Senza formaggio, per favore.', exZh:'唔要芝士，唔該。'},
  {id:'piccante', it:'piccante', zh:'辣', topic:'餐廳', emoji:'🌶️', example:'È piccante?', exZh:'呢個辣唔辣？'},
  {id:'allergico', it:'allergico', zh:'過敏', topic:'餐廳', emoji:'⚠️', example:'Sono allergico alle noci.', exZh:'我對果仁過敏。'},

  // 食物
  {id:'prosciutto', it:'prosciutto', zh:'火腿', topic:'餐廳', emoji:'🥓', example:"C'è prosciutto?", exZh:'有冇火腿？'},
  {id:'maiale', it:'maiale', zh:'豬肉', topic:'餐廳', emoji:'🐷', example:"C'è del maiale?", exZh:'有冇豬肉？'},
  {id:'pesce', it:'pesce', zh:'魚', topic:'餐廳', emoji:'🐟', example:'Prendo il pesce.', exZh:'我要魚。'},
  {id:'bistecca', it:'bistecca', zh:'牛扒', topic:'餐廳', emoji:'🥩', example:'Prendo la bistecca.', exZh:'我要牛扒。'},
  {id:'insalata', it:'insalata', zh:'沙律', topic:'餐廳', emoji:'🥗', example:'Prendo un\'insalata.', exZh:'我要一份沙律。'},
  {id:'funghi', it:'funghi', zh:'蘑菇', topic:'餐廳', emoji:'🍄', example:"Ci sono funghi?", exZh:'有冇蘑菇？'},
  {id:'antipasti', it:'antipasti', zh:'前菜 / appetizers', topic:'餐廳', emoji:'🫒', example:'Prendiamo degli antipasti.', exZh:'我哋要啲前菜。'},
  {id:'primi', it:'primi', zh:'第一道主食（意粉、飯等）', topic:'餐廳', emoji:'🍝', example:'Quali primi consiglia?', exZh:'你推薦邊款第一道主食？'},
  {id:'secondi', it:'secondi', zh:'主菜（肉、魚等）', topic:'餐廳', emoji:'🍖', example:'Quali secondi consiglia?', exZh:'你推薦邊款主菜？'},
  {id:'contorni', it:'contorni', zh:'配菜 / side dishes', topic:'餐廳', emoji:'🥦', example:'Quali contorni avete?', exZh:'有咩配菜？'},
  {id:'dolci', it:'dolci', zh:'甜品', topic:'餐廳', emoji:'🍰', example:'Avete dei dolci?', exZh:'有冇甜品？'},
  {id:'torta', it:'torta', zh:'蛋糕', topic:'餐廳', emoji:'🎂', example:'Una fetta di torta, per favore.', exZh:'一件蛋糕，唔該。'},

  // 飲品 / Café
  {id:'caffe', it:'caffè', zh:'咖啡 / espresso', topic:'Café', emoji:'☕', example:'Vorrei un caffè, per favore.', exZh:'我想要一杯咖啡。'},
  {id:'acqua', it:'acqua', zh:'水', topic:'飲品', emoji:'💧', example:'Vorrei un\'acqua.', exZh:'我想要一支水。'},
  {id:'acqua-frizzante', it:'acqua frizzante', zh:'有氣水', topic:'飲品', emoji:'🫧', example:'Avete acqua frizzante?', exZh:'有冇有氣水？'},
  {id:'acqua-naturale', it:'acqua naturale', zh:'無氣水', topic:'飲品', emoji:'💧', example:'Vorrei acqua naturale.', exZh:'我要無氣水。'},
  {id:'frizzante', it:'frizzante', zh:'有氣 / sparkling', topic:'飲品', emoji:'🫧', example:'Acqua frizzante, per favore.', exZh:'有氣水，唔該。'},
  {id:'naturale', it:'naturale', zh:'無氣 / still', topic:'飲品', emoji:'💧', example:'Acqua naturale, per favore.', exZh:'無氣水，唔該。'},
  {id:'ghiaccio', it:'ghiaccio', zh:'冰', topic:'飲品', emoji:'🧊', example:'Senza ghiaccio, per favore.', exZh:'唔要冰，唔該。'},
  {id:'latte', it:'latte', zh:'奶', topic:'Café', emoji:'🥛', example:'Senza latte, per favore.', exZh:'唔要奶，唔該。'},
  {id:'birra', it:'birra', zh:'啤酒', topic:'飲品', emoji:'🍺', example:'Vorrei una birra, per favore.', exZh:'我想要一杯啤酒。'},
  {id:'vino', it:'vino', zh:'酒 / wine', topic:'飲品', emoji:'🍷', example:'Prendo un vino rosso.', exZh:'我要一杯紅酒。'},
  {id:'rosso', it:'rosso', zh:'紅色 / 紅酒用', topic:'飲品', emoji:'🔴', example:'Un vino rosso, per favore.', exZh:'一杯紅酒，唔該。'},
  {id:'bianco', it:'bianco', zh:'白色 / 白酒用', topic:'飲品', emoji:'⚪', example:'Un vino bianco, per favore.', exZh:'一杯白酒，唔該。'},
  {id:'zucchero', it:'zucchero', zh:'糖', topic:'Café', emoji:'🍬', example:'Senza zucchero.', exZh:'唔要糖。'},

  // 付款 / 購物
  {id:'quanto-costa', it:'quanto costa', zh:'幾錢？', topic:'購物', emoji:'🏷️', example:'Quanto costa?', exZh:'幾錢？'},
  {id:'carta', it:'carta', zh:'卡', topic:'付款', emoji:'💳', example:'Posso pagare con la carta?', exZh:'可以用卡付款嗎？'},
  {id:'carta-di-credito', it:'carta di credito', zh:'信用卡', topic:'付款', emoji:'💳', example:'Posso pagare con la carta di credito?', exZh:'可以用信用卡付款嗎？'},
  {id:'contanti', it:'contanti', zh:'現金', topic:'付款', emoji:'💶', example:'Posso pagare in contanti?', exZh:'可以畀現金嗎？'},
  {id:'caro', it:'caro', zh:'貴', topic:'購物', emoji:'💸', example:'È troppo caro.', exZh:'太貴喇。'},
  {id:'economico', it:'economico', zh:'平 / 經濟實惠', topic:'購物', emoji:'🪙', example:'Avete qualcosa di più economico?', exZh:'有冇平啲嘅？'},
  {id:'cassa', it:'cassa', zh:'收銀處', topic:'購物', emoji:'🧾', example:"Dov'è la cassa?", exZh:'收銀處喺邊？'},
  {id:'camerino', it:'camerino', zh:'試身室', topic:'購物', emoji:'👗', example:"Dov'è il camerino?", exZh:'試身室喺邊？'}
];
